apiVersion: v1
kind: Pod
metadata:
  name: multi-container
spec:
  containers:
  # docker run -d --name nginx nginx
  - name: nginx
    image: nginx:stable-perl

  - name: almalinux
    image: almalinux:9
    command: ["sleep","100"]