apiVersion: v1
kind: Pod

metadata: 
   name: environment
   
spec:
  containers:
  - name: nginx
    image: nginx
    env: 
    - name: course
      valueFrom:
        configMapKeyRef:
          name: nginx-config
          key: course
    
    - name: duration
      valueFrom:
        configMapKeyRef:
          name: nginx-config
          key: timeofcours