apiVersion: v1
kind: Service

metadata: 
   name: nginx
spec:
  selector:
    project: expense
    module: backend
    environment: dev
  ports:
  - name: nginx-svc-port
    protol: TCP
    port: 80 #serviceport
    targetPort: 80 #containerport

